field: observer.ingress.vlan.name
fieldset: observer
dashed_name: observer-ingress-vlan-name
description: Optional VLAN name as reported by the observer.
example: outside
flat_name: observer.ingress.vlan.name
ignore_above: 1024
level: extended
name: name
original_fieldset: vlan
type: keyword
